language: python
dist: bionic

install:
  # Required so `git describe` will definitely find a tag; see
  # https://github.com/travis-ci/travis-ci/issues/7422
  - git fetch --unshallow
  - make testdeps
script:
  - make test

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=behave-pro-aws
      script:
          - BUILD_PR=1
          - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then BUILD_PR=0; fi
          - >
              if [ "$BUILD_PR" -eq "1" ]; then
                 cd $TRAVIS_BUILD_DIR/..
                 tar -zcf pr_source.tar.gz ubuntu-advantage-client
                 cp pr_source.tar.gz /tmp
                 ls -lh /tmp
                 cd $TRAVIS_BUILD_DIR
              fi
          - UACLIENT_BEHAVE_BUILD_PR=${BUILD_PR} make test
