language: python
dist: bionic

install:
  # Required so `git describe` will definitely find a tag; see
  # https://github.com/travis-ci/travis-ci/issues/7422
  - git fetch --unshallow
  - make testdeps
script:
  - make test

matrix:
  fast_finish: true
  include:
    - env:
        PACKAGE_BUILD_SERIES=xenial
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
