language: python
dist: bionic

stages:
 - build
 - cleanup

install:
  # Required so `git describe` will definitely find a tag; see
  # https://github.com/travis-ci/travis-ci/issues/7422
  - git fetch --unshallow
  - make testdeps
script:
  - make test

matrix:
  fast_finish: true
  include:
    - env:
        PACKAGE_BUILD_SERIES=xenial
      stage: build
      before_cache:
        - cp *deb ${TRAVIS_BUILD_DIR}/cache-artifacts
      cache:
        - directories:
          - ${TRAVIS_BUILD_DIR}/cache-artifacts
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
    - env:
        CHAD=blah
      stage: cleanup
      script:
        - ls ${TRAVIS_BUILD_DIR}/cache-artifacts
      cache:
        - directories:
          - ${TRAVIS_BUILD_DIR}/cache-artifacts
