language: python
dist: bionic

stages:
 - build
 - cleanup

install:
  # Required so `git describe` will definitely find a tag; see
  # https://github.com/travis-ci/travis-ci/issues/7422
  - git fetch --unshallow
  - make testdeps
script:
  - make test

matrix:
  fast_finish: true
  include:
    - env:
        PACKAGE_BUILD_SERIES=xenial
      stage: build
      cache:
        - directories:
          - cache-artifacts
      install:
        - make travis-deb-install
      script:
        - make travis-deb-script
        - rm -f cache-artifacts/*deb
        - cp *deb cache-artifacts/
    - env:
        CHAD=blah
      stage: cleanup
      cache:
        - directories:
          - cache-artifacts
      script:
        - ls cache-artifacts
